version: '3.9'
services:
  beyond:
    build: .
    container_name: beyond
    ports:
      - "5000:5000"

  db:
    image: postgres:13.2
    container_name: postgres
    environment:
      POSTGRES_USER: beyond
      POSTGRES_PASSWORD: beyond
      POSTGRES_DB: beyond
    expose:
      - 5432
    ports:
      - 5432:5432
